P-AS/srb2-legacy

- src/Makefile.d/versions.mk
Got this compilation error when trying to compile a debug build with `DEBUGMODE=1`:
```
cc: warning: O0: linker input file unused because linking not done
cc: error: O0: linker input file not found: No such file or directory
```
This was caused by a missing `-` on the `O0`, causing it to be treated as a file instead, and since this was combined with `-c`, it tried to treat the `O0` as a linker file and failed due to a missing file.
> Fix debug build compilation

- src/g_game.c
- src/g_game.h
- src/p_map.c
With a fast enough character and/or with steep enough stairs, all momentum can be lost if you travel up them too quickly. This was caused due to an adjustment error when calculating step collision, where step-ups failed to take the difference in height of the collision box into consideration, which caused it to check only the top and bottom steps and thus think it was traveling higher than it actually was and block the movement.
This patch fixes this by updating the Z-axis to the highest point of the stairway, which causes it to always calculate the step distance from the highest point. That way, we can be sure that it always calculates the step height from the correct Z-axis.
The bug can be triggered most easily on [Technology Station](https://mb.srb2.org/threads/july-august-2015-voting.2 …
> Fix loss of momentum when travelling up multiple steps in a tic

- src/p_inter.c
If an object's SOC definition had it's painstate set to `S_NULL`, the game would segfault when that object took damage. This was caused by the (to me) very iconic lack of a `P_MobjWasRemoved` check after the state was set in `P_DamageMobj`.
This bug can be triggered on [Quickman 2](https://mb.srb2.org/threads/january-february-2015-voting.23188/) by simply being hit. Note that it does not trigger consistently unless the game is compiled with `DEBUGMODE=1`.
> Fix segfault when painstate is S_NULL

- src/console.c
A minor goof while backporting native keyboard layout in #6, where console input would be blocked due to misplaced condition on event types. This event is handled further down, but this check blocked it since it exited early and required the console to be opened, which isn't really possible from the console on a dedicated server.
> Fix console input

- src/hardware/hw_main.c
- src/p_slopes.c
- src/p_slopes.h
- src/r_things.c
- src/r_things.h
After Slopes were added to 2.1, the OpenGL sprite shadows were not updated to reflect this and currently break on slopes. This MR fixes that issue.
> Fix GL Sprite shadows on slopes

- src/Makefile.d/versions.mk
- src/d_clisrv.c
- src/dehacked.c
- src/hu_stuff.c
- src/p_spec.c
- src/s_sound.c
- src/sdl/i_system.c
- src/v_video.c
When compiling srb2-legacy I get these warnings about stringop-truncation. 
this simply fixes those warnings from occuring
> Fix stringop-truncation warnings

- src/d_netcmd.c
- src/m_menu.c
- src/m_menu.h
- src/sdl/i_system.c
- src/sdl/i_video.c
- src/sdl/sdlmain.h
Before 2.2, SDL's joystick subsystem would be shut down before the game started. This meant that Gamepads could only be recognized at game startup, and unplugging and replugging a gamepad would not work. This simply ports joystick hotplugging from 2.2
> Joystick Hotplugging 

- src/z_zone.c
- src/z_zone.h
This backports 2.2's zone allocations to 2.1, giving us the benefits of aligned memory accessing, some minor optimizations and better debugging mechanisms. Pretty straightforward backport, was just a copy-paste and some adjustments for the `PU_*` constants.
@P-AS Off-topic, but FYI, me and KitsuWhoaa have been on the old #srb2fun IRC channel on EsperNet and been experimenting with Legacy there - they've shown a lot of interest in the project, and we've also discovered some bugs together. Feel free to join if you're interested, and want to contribute to the discussion (assuming we're not asleep). :)
> Backport z_zone allocations

- src/CMakeLists.txt
Minimum required code to get SRB2 Legacy to compile and run on Haiku using CMake. I'm not going to go through all the effort of getting all components working like I did with 2.2, though - only singleplayer has been tested and confirmed to work as expected.
> Add Haiku build

- src/d_think.h
- src/p_local.h
- src/p_mobj.c
- src/p_setup.c
- src/p_tick.c
Backport of [!2200](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2200) , basically makes mobj spawning faster by caching removed mobjs and reusing them when needed.
> Cache and reuse removed mobjs when spawning mobjs (Backport of MR !2200)

- src/p_mobj.c
Fixes an old bug that has been around for a long time, but has been fixed in 2.2. Can be triggered with a debug build by switching color after switching skin to Inazuma.
Upstream patch: https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1963
> Fix segfault when deleting first overlay in overlaycap

- src/filesrch.c
[From the original merge request page](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2198):
currently, SRB2 tries to look up files recursively when searching for game files. while this gives us a flexible system, it can become a performance issue during startup since a lot of files tend to get dumped in the game directory after a while (stuff like downloaded addons, logs, lua files, etc). this can cause startup and load times to increase over time as the amount of files increases, and can even even hit the point where it can take more than 5 seconds to start up!
the cause of these slow load times, though, is a call to stat for every file in the directory. this makes the kernel resolve and look up every file twice, which increases the amount of time it takes to search substantially. …
> Improve file search performance on Linux and FreeBSD 

- src/dedicated/i_system.c
- src/sdl/i_system.c
Backport of https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2396 and https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2493, greatly improving load times when finding WAD files.
> Don't traverse the entire HOME directory to find wads

- src/Makefile.d/nix.mk
Most likely a leftover from 2.1, since IPX is not really a thing anymore and SRB2 doesn't even use it.
> Fix FreeBSD build

- src/mserv.c
So I've gone through the effort of setting up a master server for 2.1, which SRB2 Legacy can use. I've done some local testing and it works just fine both in a test environment and when deployed in production, but so far, I haven't been able to do any large-scale testing because you can only do so much alone. So if you run into any issues, please report it either here or on the Codeberg repository below.
The full source code for the master server can be found here: https://codeberg.org/Hanicef/srb2ms-evo
**NOTE**: As for the domain name, I plan to fork 2.2 once the last version of it releases under the name SRB2 Classic, and since the master server is compatible with both versions, I didn't see a reason to buy 2 domains for the same software, so 2.1 will be using SRB2 Classic's domain. …
> Switch to use new 2.1 master server

- src/st_stuff.c
- src/st_stuff.h
And including splitscreen.... hell of a code. It always irked me that 2.1's HUD is poorly made for non-recomended resolutions so i decided to fix it.
So yeah it makes the HUD to look better without any weird padding like the score, time and rings being off, the weapon rings being on the left, the race countdown off-centered, and the CTF status never positioning correctly.
> Fix HUD padding in most cases for non-green resolutions

- src/s_sound.c
SDL_Mixer's native MIDI was broken because the game tried to play audio before Mix_OpenAudio has been called. This resulted in the native MIDI backend being marked as broken, falling back to the next one.
Fix it by checking if sound has been initialised before trying to play anything on musicpref cvar change.
Fixes: 2544f548cda0 ("Add musicpref console variable (backport of MR !939)")
> Fix SDL_Mixer native MIDI

- src/CMakeLists.txt
- src/sdl/CMakeLists.txt
Debug builds fail with:
```
CMake Error at src/sdl/CMakeLists.txt:141 (add_custom_command):
TARGET 'SRB2SDL2' was not created in this directory.
```
This is a partial backport of
a015be2a54d3 ("cmake: Build all deps and static link") and efba50c83c73 ("CMAKE: Add SRB2_DEBUG_INSTALL to toggle *.debug in install/package") that solves this issue.
> CMake: Fix Debug builds

- src/m_menu.c
Minor regression caused by native keyboard layout, where keypresses in menus would pass through the menu and be registered in-game, causing you to move around with WASD when typing your player name in player setup, for example.
> Fix keyboard input in menus registering in-game

- src/mserv.c
Fixes the issue mentioned in #27, where the master server socket would fail to connect due to the existing socket being in a bad state. It seemed to be caused by old sockets not being deallocated properly on a failed connection attempts, so it would just sit around in memory until the socket count would be exhausted.
I plan to overhaul the master server logic later to add IPv6 support as well as make it all background-threaded, so updates to the master server doesn't cause stuttering on a server with a high latency to the MS. This is just a lesser hack to fix the immediate problem with it.
> Fix bad file descriptor error on master server socket

- src/CMakeLists.txt
- src/sdl/CMakeLists.txt
Haiku CMake build refused to work on my system on the latest commit, and I managed to get it working after some tweaking. The problem is that Haiku has it's system stuff in unconventional places, so standard dependency resolution doesn't always work. This can be solved by adding a dependency using the `CONFIG` setting on the dependency, and another without it too, so it looks in standard directories.
This patch also makes `SDL2` a required dependency since without it, it obviously won't link correctly, so we really shouldn't allow it.
> Fix Haiku build

- src/hardware/hw_main.c
This fixes a potential segfault that can occur when OpenGL draws precipitation mobjs. In a nutshell, if a precip mobj is being referenced by another object, it's removal will be delayed to prevent references to it to become dangling, but since the object won't be `NULL` in that case, you can still access it, but it's data is not valid. This can trigger a segfault if it only does a `NULL` check before accessing child elements of the object, and the correct thing to do is to use `P_MobjWasRemoved` instead to make sure that the object is actually valid before it's being used.
This crash can happen in Subarashii in the hub map, shortly after the map has loaded in.
> Fix potential segfault when rendering precipitation in OpenGL

- src/mserv.c
An oversight in #43 would cause register and update requests to the master server to be sent in bursts of packets rather than just sending a single one. This was caused by the request time being updated in the background thread rather than on the main thread, and as a result, it would be possible for another thread to start if the update wasn't finished before the main thread, causing it to send another request to the MS again.
This changes it so the update time is set on the main thread rather than the background thread, so it won't send an update again if the background thread hasn't finished yet.
> Fix clients sending register messages is bursts to MS

- src/d_net.h
- src/m_menu.c
- src/mserv.c
- src/mserv.h
While IPv6 support is almost there, there is one glaring problem with fully implementing it that was only now discovered. The problem is that the buffer for IP addresses on the master server is only 16 bytes, which is not large enough to fit an IPv6 address. As a backwards-compatible workaround, I added a new message type named `GET_EXT_SERVER_MSG` which is the same as the old `GET_SHORT_SERVER_MSG`, but with a 40-byte large buffer for IP addresses instead, which is large enough to fit an IPv6 address. In addition to this, the old message type will no longer send IPv6-enabled servers anymore, as chances are the address won't fit the buffer.
This patch also finally implements the IPv6 tag on servers that has an IPv6 address, like 2.2 does, so you can now differentiate IPv4 servers from …
> Switch to use the extended server list queries

- src/sdl/i_system.c
Blindly copying a set amount of bytes out of a variable length buffer is not advised.
> Fix out of bounds access when pasting from clipboard

- src/Makefile.d/features.mk
Fixes the following issue when building with VALGRIND=1 by simply not linking against the libraries, like upstream.
```
Linking lsdl2srb2legacy.debug...
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/valgrind/libcoregrind-amd64-linux.a(libnolto_coregrind_amd64_linux_a-m_main.o): in function `_start':
(.text+0x0): multiple definition of `_start'; /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/Scrt1.o:(.text+0x0): first defined here
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/valgrind/libcoregrind-amd64-linux.a(libnolto_coregrind_amd64_linux_a-m_main.o): relocation R_X86_64_32S against symbol `vgPlain_interim_stack' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
```
> Fix linking with valgrind

- src/filesrch.c
In the addons menu, if you search for an addon and then add it, the game could potentially crash once the addon has finished loading. The reason is due to a use-after-free in the addon list, where when an addon is added, the menu will be refreshed to mark the newly added addon as added, but since the search list wasn't properly cleared, it would use old references that had been deallocated in the search list, which could potentially crash.
This patch fixes this by clearing the search list when the addon list is being reloaded, so it will be refreshed anew upon adding an addon.
> Fix use-after-free when loading addons after searching addons

- src/i_tcp.c
Once again, Haiku's quirky network stack revealed a bug in SRB2. In this case, Haiku would crash if it fails to resolve an address, because if it failed to resolve it, it would return a non-zero status code, but in that case, SRB2 would still pass the address info data to `I_freeaddrinfo`, which is not allowed on Haiku and would then consequently crash.
This changes the logic so it just returns immediately upon a failure, since it's bound to return a failure anyway if `I_getaddrinfo` failed.
> Fix IP resolution on Haiku

- src/m_cheat.c
- src/p_mobj.h
When rendering precip objects, the logic assumes that `precipmobj_t` and `mobj_t` have the same fields aligned in it. This allows it to use the same logic for both types, reducing redundant code (SRB2 actually following DRY principle, that's a first-timer), but of course, it breaks if any fields are misaligned.
In this case, it wasn't, as the new coordinate fields were missing on `precipmobj_t`, causing state updates during rendering to read the wrong field when casted to an `mobj_t` and consequently segfault the game. Adding these fields to `precipmobj_t` fixes the issue.
> Fix segfault when rendering precip objects

- src/d_clisrv.c
If an address from the MS fails to resolve, the engine would just bail, and not attempt to resolve any other addresses, resulting in an incomplete server list. This was discovered thanks to #53, as Haiku would crash is this case, which kinda revealed the problem.
Also, this is not the first time Haiku has revealed a bug in netcode - it made big revelations in 2.2 when porting it for the first time, so that's another reason to keep the port alive, even if nobody uses it (maybe consider a HaikuPorts package?).
> Fix server listing refusing to list servers on resolution failure

- src/p_saveg.c
- src/r_fps.c
Thinkers were being freed by mistake due to misleading indentation.
> Fix user after free when joining a netgame

- src/dedicated/CMakeLists.txt
Similar to f84c5aae90a7 ("CMake: Fix Debug builds") but for dedicated server builds.
> CMake: Fix dedicated Debug builds

- src/dehacked.c
When all admins leave, adminplayers[0] ends up being -1, resulting in playeringame[-1] which is out of bounds.
This fixes the issue by ensuring that adminplayers[0] is within playeringame's range.
> Prevent out of bounds access in Lua admin

- src/p_map.c
- src/p_mobj.c
Occurred on Sonic Adventure map pack, if rings are removed as they are being pulled, the game could potentially segfault as there are no checks that makes sure the mobj is still valid.
> Fix segfault when rings are attracted

- src/d_clisrv.c
- src/mserv.c
- src/mserv.h
So, a big goof on my end: when IPv6 server listing was introduced to the MS, I didn't think of the fact that the buffer used for registering on the MS is the same as the one used for querying, so it ended up sending a larger packet than the MS was expecting, causing servers to fail to register. The MS actually ignores the host part and uses the IP of the source connection instead when registering to not make it too easy to spoof IP addresses, so it doesn't need to be expanded for IPv6.
This patch now splits these packet types into two different types, so everything should now be in working condition again.
> Fix MS registration after IPv6 listing was introduced

- src/d_clisrv.c
When the last player quits the special stage, count ends up being 0, resulting in a division by zero and a SIGFPE, killing the server.
Simply check that count is > 0 before trying to divide. No point in trying to distribute rings when there are no players left.
> Fix server crash when clients quit special stages

- src/r_draw.c
If `starttranscolor` is set to a value beyond 240, the game could segfault due to a buffer overflow when the color ramp is being written. This happened because the colormap is 256 bytes long and the ramp requires 16 colors, so if the start of the ramp is beyond 240, it would write 16 colors up to that color, which is beyond the 256 bytes that the colormap contains. Truncating the write length in that case fixes the problem.
> Fix overflow when starttranscolor is beyond palette number 240

- src/hu_stuff.c
- src/m_menu.c
`CHAT_WordWrap` and `V_WordWrap` both return a newly allocated string from it's input, but in numerous places where we call those functions, we don't deallocate the memory afterwards. This caused serious memory leaks, where the memory usage could go up to 3GB over just about 15 minutes when playing multiplayer. This patch properly deallocates the strings afterwards to fix the leaks.
> Fix memory leak caused by word wrapping

- src/d_clisrv.c
- src/d_netfil.c
This patch allows increasing `maxsend` to any number as you like, or remove the limit entirely by setting it to -1. This is invaluable for hosters, since limits to download sizes tend to be problematic when picking addons and can even render some addons not viable when doing serious hosting. By removing this limit, hosters won't need to worry about this, and focus can instead be put on curating a good set of addons for a server.
> Remove maxsend limits

- src/d_clisrv.c
Set maximum of `maxsend` and `downloadspeed` to their 2.2 values which are 50MB->200MB and 32->300 respectively.
> Updated some download limits to 2.2

- src/f_finale.c
On the game evaluation screen, after the credits, the emerald rotation logic weren't properly handling uncapped, so running at any framerate higher than 35 would cause it to spin faster than intended. At very high framerates (+500 fps), the emeralds would spin so fast that it would be impossible to tell which emeralds were missing. This patch fixes this by measuring time using `I_GetTime` instead, which causes it to position itself according to ticrate instead. While this is not the best solution, since it actually locks the emeralds to the ticrate, it at least solves the problem for the next version.
> Fix emeralds spinning abnormally fast on evaluation screen

- src/d_main.c
- src/r_main.c
- src/r_main.h
- src/st_stuff.c
When running at higher framerates, the emerald finder sound was running alongside HUD logic, and as a result, wasn't capped to the 35 ticrate. This caused the sound to play repeatedly at once, which caused it to be louder than intended, with no limits to the amount of times it could play. On very high framerates, this sound could overlap so many times that it became ear-shatteringly loud.
To fix this, a new variable, `renderisnewtic`, is introduced that is set to true for the first frame in a tic. This allows us to prevent the sound from playing twice if a new tic hasn't started, causing it to only play once per tic as intended.
> Fix emerald finder sound getting louder on higher framerates

- src/d_main.c
- src/dehacked.c
- src/doomdef.h
- src/g_game.c
- src/g_game.h
- src/p_saveg.c
- src/p_saveg.h
The SRB2 directory can get quite messy and savefiles participate in that.
This PR put saves in a separate folder. This folder can be specified with the `-savedir` command-line parameter and is by default "save".
> Put saves in a separate folder

- src/CMakeLists.txt
This adds the equivalent of `DEBUGMODE=1` to CMake, so debugging can be done using CMake.
> Add SRB2_CONFIG_DEBUGMODE to CMake build

- src/d_clisrv.c
- src/m_menu.c
- src/mserv.c
- src/mserv.h
This removes the old UDP MS socket, which is no longer necessary due to srb2ms-evo's internal scheduler just querying servers directly now, not to mention that it doesn't even have a UDP socket that listens for connections, so it can't even respond to queries made via UDP.
Closes #60
> Remove MS UDP socket

- src/dedicated/i_system.c
- src/sdl/i_system.c
This fixes a bug in the console input on Windows that forced the console input to be uppercased when inputted via the command prompt, which is normally the case for dedicated servers. The issue is that `MapVirtualKey` is meant to be used for key mapping and thus ignores modifier keys and forces uppercase - for actual keyboard input, `uChar.AsciiChar` is meant to be used (and `uChar.UnicodeChar`, but right now SRB2 doesn't support Unicode, so we can't use that yet).
> Fix console input via command prompt being uppercase on Windows

- src/hardware/hw_cache.c
- src/m_aatree.c
- src/m_menu.c
- src/p_spec.c
- src/r_draw.c
This patch fixes the following memory leaks:
* The texture cache in OpenGL never deallocated mipmap textures properly.
* The save menu didn't deallocate colormaps every frame.
* Attached FOFs in sectors were allocated `PU_STATIC`, so they weren't deallocated on map change.
Finally, because I was digging so damn long to find this bug, I also noticed that the binary tree used in `AATree` was not balancing properly, which could slow down reads from it. This has been fixed now by properly implementing tree balancing. For info on how to balance binary trees correctly, see https://adrianmejia.com/self-balanced-binary-search-trees-with-avl-tree-data-structure-for-beginners/
> Fix various memory leaks

- src/d_clisrv.c
Ok, so for some goddamn reason, SRB2 was just openly exposing player's IP addresses to anyone that knows how to send a `PT_PLAYERINFO` packet, which is quite frankly moronic. Let's not do that.
> Don't expose IP addresses of players in PT_PLAYERINFO packets

- src/dedicated/i_main.c
- src/doomdef.h
- src/i_system.h
- src/sdl/i_main.c
- src/sdl/i_system.c
This patch adds the new signal handler from [!530](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/530) which adds a forked signal handler which can be disabled with the `-nofork` command line parameter. Also adds backtrace support from [!1288](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1288) which prints a backtrace whenever the game crashes
> Backport the 2.2 signal handler and backtraces for Unix systems

- src/d_clisrv.c
Backport of https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2046, patch has been running on The Gaming Den for a few days and seems to work just fine.
> Prevent dropped ticcmds due to interp timing jitter

- src/hu_stuff.c
- src/m_aatree.c
- src/m_misc.c
- src/z_zone.c
- src/z_zone.h
This hopefully fixes the final leaks in the engine, and most importantly the serious memory leak that causes memory use to skyrocket in OpenGL. Now, memory use remains on a steady 230 MB on Subarashii.
The cause was due to the chat log not deallocating it's string that it uses for each line, which massively wastes memory as it's being allocated multiple time for each frame. There was also another leak when saving configuration that was also fixed in the process.
> Fix remaining leaks

- src/hardware/hw_main.c
Port of [!1005](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1005)
It replaces the old bubble sort algorithm with a quick sort algorithm making it much faster and also more accurate
Look at the "Drwnode sort" stat
Before:
After:
> Faster and more correct OGL transparent surface sorting

- src/lua_script.c
- src/w_wad.c
- src/w_wad.h
Backports the PK3 loading code from Kart from 2.2 
The main changes are:
1. The use of SRB2 2.2's ResGetLumpsZip adds proper handling of PK3s with comments and extra fields.
2. PK3 handling code no longer expects the presence of trailing directory entries (as created by SLADE), though it still handles them.
3. The W_VerifyFile function is extended to support PK3s, allowing them to be marked "unimportant", i.e. loadable clientside without being present on the server – as was already possible with WADs, especially for music replacement.
What this means is that files created by any .zip archiver will work in SRB2 and Certain mods, like music and shaders will not modify the game if loaded in a PK3
> Backport PK3 loading fixes from Kart

- src/p_polyobj.c
- src/p_tick.c
Fixes two issues caused by uninitialized variables on polyobject thinkers
"references" being uninitialized caused them to not be freed by P_RemoveThinkerDelayed in many cases
"cachable" being uninitialized was causing undefined behaviour when trying to spawn mobjs from the mobjcache as it interpreted polyobject thinkers as being cachable
> Fix issues with uninitialized variables on polyobject thinkers

- src/screen.c
- src/sdl/i_video.c
Backport of an old 2.2 fix that fixes z-fighting in OpenGL for the most part. It simply increases the depth buffer to make up for the lost accuracy on polygons that are further away from the camera.
> Fix z-fighting in OpenGL

- src/d_clisrv.c
Adds Kart's dedicated server idle which freezes the server if no nodes are there for more than 10 seconds, saving resources.
> Port Kart's dedicated server idle

- src/dedicated/i_main.c
- src/p_user.c
`cv_grshearing` doesn't exist on dedicated builds since the concept of rendering doesn't exist, so it needs to be excluded from that build type.
The patch also fixes an unused variable warning in dedicated builds.
> Fix dedicated build

- src/d_clisrv.c
While, I was making #97, i forgot to update the indicator colors to a 2.1 color indexes and instead it still was using 2.2 color indexes.
Right now is fixed, though player information is still kinda buggy (which also happens in 2.2) and I would simply remove it since i dont find it very useful aside for knowing player's names and status if it's playing or in spectator (tbh colors ay simply not give a proper indicator if you're colorblind to being with).
In the meantime colors now display correctly.
> Fix indicator colors of players in server info view

- src/blua/Sourcefile
- src/blua/linit.c
- src/blua/loslib.c
- src/blua/lualib.h
Ports the OS lua library to 2.1 which has been stripped of basically everything except time related functions, it can be used for seeding RNG or getting time.
Example script using the library 
[clock.lua](https://git.do.srb2.org/-/project/2/uploads/a4364367f66e98ccebff24cd1fd6231f/clock.lua)
> Paired down OS Lua library

- src/m_menu.c
- src/screen.c
- src/v_video.c
- src/v_video.h
Adds FPS/TPS counter sizes from SRB2Classic where you can select between like "Normal", "Thin" and "Small".
> Add FPS/TPS counter sizes

- src/hardware/hw_data.h
- src/hardware/hw_md2.c
Backports the blend texture code from 2.2, minus `TC_RAINBOW`, because we don't have it in 2.1 which supports translation colormaps, which for example allows bosses to "flash" when they are hit and brak eggman to turn full white when he is hit.
It also makes skincolors with duplicate skincolor indices smoother
For example, let's take a look at Teal's ramp
A lot of duplicated indices, right?
**Before:**
**After:**
Notice how in "After" the transitition between the skin tones are lot more gradual
> Update blend texture code

- src/blua/liolib.c
- src/d_clisrv.c
- src/d_clisrv.h
- src/d_main.c
- src/d_net.c
- src/d_netcmd.c
- src/d_netcmd.h
- src/d_netfil.c
- src/d_netfil.h
- src/lua_baselib.c
Backports the Lua I/O library from 2.2 which supports sending files over lua with `io.opennew` and `io.open` is a wrapper for `io.openlocal`  (to keep compatibilty with 2.1 mods that used I/O) as well as a bunch of other changes. I've made an edited version of `sendcolor.lua` that supports 2.1 and it works functionally the exact same as the 2.2 version (save as .lua)
[sendcolor-v7-21edit.lua.txt](https://github.com/user-attachments/files/21244097/sendcolor-v7-21edit.lua.txt)
> Lua I/O library from 2.2
