- src/console.c
- src/d_event.h
- src/dummy/i_system.c
- src/hu_stuff.c
- src/i_system.h
- src/m_menu.c
- src/sdl/i_main.c
- src/sdl/i_system.c
- src/sdl/i_video.c
Backport of [!1952](https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1952) and related patches, adjusted for 2.1's input code.
> Add support for native keyboard layout

- src/sdl/i_main.c
Now there can be more than 1 logfile, like in 2.2. Use the command line parameter `-nolog` to disable them
> Log Directory 

- src/r_main.c
Backport of https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2168, giving significant performance improvement over the old solution. See the mainline PR for more info.
> Avoid branch prediction slowdowns in R_PointOnSide

- src/CMakeLists.txt
- src/Makefile.d/dedicated.mk
- src/Makefile.d/nix.mk
- src/Makefile.d/platform.mk
- src/d_main.c
- src/dedicated/CMakeLists.txt
- src/dedicated/Sourcefile
- src/dedicated/dosstr.c
- src/dedicated/endtxt.c
- src/dedicated/endtxt.h
- src/dedicated/i_main.c
- src/dedicated/i_sound.c
- src/dedicated/i_system.c
- src/dedicated/i_video.c
- src/m_menu.c
Backport of https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2246. Code was actually rewritten from scratch to better fit 2.1's code, although it still works identically to 2.2's.
Also, as a bonus, here's a SRB2 Legacy-exclusive feature: you can build the dedicated build with CMake by specifying `-DSRB2_CONFIG_DEDICATED=1` when configuring the project, giving you a second option to build the dedicated build. Note that this has only been tested on Linux, so it's unknown if the CMake dedicated build will work on Windows (if not, you can always build the Makefile build, which has been tested and confirmed to work on Windows).
> Add dedicated build

- src/d_clisrv.c
- src/d_clisrv.h
- src/d_net.c
- src/i_tcp.c
This backports 2.2's i_tcp.c, giving us the following features:
* IPv6 support
* LAN discovery
* Random port assignment
* Unlimited bans
* Numerous bug fixes
> Backport i_tcp.c from 2.2

- src/dedicated/i_system.c
- src/sdl/i_system.c
Backport of https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2360, which is now relevant to me since we're setting up a 2.1 server alongside the master server, and it's connected to the bridge that exists on The Gaming Den. Very minor issue, but I'd rather not have to deal with over 5 second delays on bridged messages.
> Fix TTY input latency

- src/CMakeLists.txt
- src/Makefile
- src/Makefile.d/dedicated.mk
- src/Makefile.d/sdl.mk
- src/d_main.c
- src/i_threads.c
- src/i_threads.h
- src/mserv.c
This is a refactor of the master server code that involves the following:
* Master server socket is no longer global, which helps eliminate bugs due to improper file descriptor handling.
* Registering and updating on the MS is now done on a background thread, eliminating stutters when updating on the MS.
* Code logic has been significantly simplified.
Next up, I will tackle IPv6 support for this, then the MS is pretty much done from the game logic perspective.
> Master server code refactor

- src/CMakeLists.txt
- src/Makefile
- src/Makefile.d/dedicated.mk
- src/Makefile.d/sdl.mk
- src/d_main.c
- src/i_threads.c
- src/i_threads.h
- src/mserv.c
Round 2 of #41, this time I've made sure that it actually builds on Windows (I thought I tested that, but apparently I didn't). The cause was due to outdated paths when backporting `i_threads.c` from 2.2, which wasn't accounted for on the Windows build. Other than that, the build is identical.
> Master server code refactor, round 2

- src/mserv.c
Adds the necessary code logic to be able to register an IPv6 server on the master server. Note that this does *not* add any visual indicator for IPv6-enabled servers - I plan to do this for another patch to keep this patch focused.
> Add support for registering IPv6 servers on the MS

- src/z_zone.c
Something similar is already implemented for valgrind.
> ASan: Poison memory allocation linked list

- src/z_zone.c
When the ASAN poisoning was introduced, it failed to cover a special case for debug builds in Z_ReallocAlign, which could cause that function to falsely report bad memory accesses even though they were not valid. The issue was that the poisoning was happened too late in the function, so an ID check on the memory block happened before the unpoison, triggering a false positive. This adjusts it so it unpoisons the memory before accessing it to get rid of the false positive.
> Fix false positive with ASAN poisoning in Z_ReallocAlign

- src/doomtype.h
- src/hardware/hw_batching.c
- src/hardware/hw_batching.h
- src/hardware/hw_main.c
- src/lua_consolelib.c
- src/lua_hudlib.c
- src/lua_infolib.c
- src/lua_maplib.c
- src/lua_mobjlib.c
- src/lua_playerlib.c
- src/lua_script.c
- src/lua_script.h
- src/lua_skinlib.c
- src/p_local.h
- src/p_mobj.c
- src/p_slopes.c
- src/r_main.c
- src/r_main.h
- src/r_things.c
This ports all major 2.2 optimizations I've done to legacy, giving a massive performance boost even when heavily modded. I will dig deeper later to find optimizations done by others - I'm just doing mine first since those are the ones I know of.
Performance test on Kimokawaii with numerous addons loaded, on The Gaming Den (since I'm too lazy to curate addons for this):
**NOTE**: Since this is a considerable change on the code, this need to be tested thoroughly so everything is still working as intended.
> Port all major 2.2 optimizations

- src/d_netcmd.c
- src/doomstat.h
- src/g_game.c
- src/g_game.h
- src/lua_hud.h
- src/st_stuff.c
- src/st_stuff.h
https://github.com/SRB2EventZ/SRB2FusionAdvance/pull/11 but with some minor additional changes. Note that it is currently disabled in splitscreen.
> Input display

- src/hu_stuff.c
- src/p_setup.c
Big fuckup on my end: I missed some `HAVE_BLUA` directives that were left in the codebase which was causing issues - this patch should get rid of the last of em.
> Remove remaining HAVE_BLUA directives

- src/hardware/hw_main.c
- src/hardware/r_opengl/r_opengl.c
- src/r_fps.c
This patch backports the following fixes:
* https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1051
* https://git.do.srb2.org/STJr/SRB2/-/merge_requests/1114
* https://git.do.srb2.org/STJr/SRB2/-/merge_requests/2408
Fixes #80
> Backport shearing fixes

- src/p_sight.c
Backport of https://git.do.srb2.org/Hanicef/SRB2Classic/-/commit/08e703d0c24cb9958057bec603991d53836d8d5c, optimizes the sight check algorithm significantly by applying the same algorithm as the BSP traversal optimization.
> Optimize P_DivlineSide

- src/m_menu.c
Fixes issue #93 and adds a little quality of life thing
> Fixes issue #93 and adds little QOL thing

- src/d_clisrv.c
- src/d_clisrv.h
Port from the [SRB2 Classic](https://git.do.srb2.org/Hanicef/SRB2Classic/-/merge_requests/18) version
~~**NOTICE:** It may break (or not) the process of cheking server files since it's totally different since 2.2, and may result in no longer working correctly. Otherwise this PR is safe to merge if no issues with joining modded servers are encountered.~~
Works correctly without issues with modded servers.
> Display server information before joining

- src/d_main.c
- src/d_player.h
- src/doomdef.h
- src/hardware/hw_defs.h
- src/hardware/hw_main.c
- src/hardware/r_opengl/r_opengl.c
- src/lua_playerlib.c
- src/p_local.h
- src/p_saveg.c
- src/p_user.c
- src/r_draw8.c
- src/r_main.c
- src/r_main.h
- src/r_segs.c
- src/r_sky.c
- src/r_things.c
Adds `viewollangle` from 2.2 which can be used in lua scripts and also, as a bonus added the `viewroll` CVar to rotate the player camera on slopes.
> Add view rolling

- src/d_clisrv.c
- src/m_menu.c
This lets the "Join last server" option also work if you used the "connect" command to connect to a server
> Let "connect" command also save to lastserver

- src/sdl/i_video.c
also know as "fix #145", no matter how hard i was shaking my phone nothing was happening so i think this issue is pretty much fixed, ![heres](https://drive.google.com/file/d/19boLUgkE4oghs9F8ARxOqGKLhUTet-ex/view?usp=sharing) an apk i compiled of this
> (android) fix using accelerometer as arrow keys
